apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname
  namespace: appnamespace
  labels:
    app: appname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      hostNetwork: false
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: php
        image: registry.hub.docker.com/{replace it}
        #env:
        #- name: ENV_VAR_NAME
        #  valueFrom:
        #    secretKeyRef:
        #      name: appname-envs
        #      key: secretkey
      - name: nginx
        image: registry.hub.docker.com/{replace it}
        ports:
          - containerPort: 80
