apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #uncomment if https
  #annotations:
    #cert-manager.io/issuer: appname
    # only https force
    #traefik.ingress.kubernetes.io/router.middlewares: appnamespace-https-appname@kubernetescrd
    # only X-Forwarded-Proto: https
    #traefik.ingress.kubernetes.io/router.middlewares: appnamespace-appname@kubernetescrd
    # both
    #traefik.ingress.kubernetes.io/router.middlewares: appnamespace-appname@kubernetescrd,appnamespace-https-appname@kubernetescrd
  name: appname
  namespace: appnamespace
spec:
  rules:
  - host: "{domain here}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: appname
            port:
              number: 80
  # tls:
  #   - hosts:
  #     - {domain here}
  #     secretName: ingress-secret
