apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #uncomment if https
  #annotations:
    #cert-manager.io/issuer: appname
    #traefik.ingress.kubernetes.io/router.middlewares: appnamespace-appname@kubernetescrd
    ##traefik.ingress.kubernetes.io/router.middlewares: appnamespace-https-appname@kubernetescrd
  name: appname
  namespace: appnamespace
spec:
  rules:
  - host: "{domain here}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: appname
            port:
              number: 80
  #uncomment if https
  #tls:
  #- hosts:
  #  - {domain here}
  #  secretName: ingress-secret
